version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./hackerspace.db:/app/hackerspace.db:z
      - ./translations.py:/app/translations.py:z
      - ./static/uploads:/app/static/uploads:z
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
